name: Run tests

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Makefile.local.test
        run: |
          cd library
          make -f Makefile.local.test
